import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/section/Header";
import Footer from "./_components/section/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="!font-sf-pro">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
